In [1]:
import pandas as pd
from pandas import json_normalize
import time
import json
import pygsheets
import gspread
from oauth2client.service_account import ServiceAccountCredentials as SAC
from gspread_dataframe import get_as_dataframe, set_with_dataframe

In [80]:
url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/05-14-2021.csv"
df = pd.read_csv(url)
df = df[df['Country_Region']=='Taiwan*']
print(df)

     FIPS Admin2 Province_State Country_Region          Last_Update   Lat  \
643   NaN    NaN            NaN        Taiwan*  2021-05-15 04:20:58  23.7

     Long_  Confirmed  Deaths  Recovered  Active Combined_Key  Incident_Rate  \
643  121.0       1290      12     1107.0   171.0      Taiwan*        5.41635

     Case_Fatality_Ratio
643             0.930233

In [13]:
for i in range(15,32):
    url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/05-"+str(i)+"-2021.csv"
    df2 = pd.read_csv(url)
    df2 = df2[df2['Country_Region']=='Taiwan*']
    df = pd.concat([df, df2], ignore_index=True)
print(df)

    FIPS Admin2 Province_State Country_Region          Last_Update   Lat  \
0    NaN    NaN            NaN        Taiwan*  2021-05-15 04:20:58  23.7
1    NaN    NaN            NaN        Taiwan*  2021-05-16 04:20:49  23.7
2    NaN    NaN            NaN        Taiwan*  2021-05-17 04:20:34  23.7
3    NaN    NaN            NaN        Taiwan*  2021-05-18 04:20:33  23.7
4    NaN    NaN            NaN        Taiwan*  2021-05-19 04:20:42  23.7
5    NaN    NaN            NaN        Taiwan*  2021-05-20 04:21:05  23.7
6    NaN    NaN            NaN        Taiwan*  2021-05-21 04:20:43  23.7
7    NaN    NaN            NaN        Taiwan*  2021-05-22 04:20:45  23.7
8    NaN    NaN            NaN        Taiwan*  2021-05-23 04:20:51  23.7
9    NaN    NaN            NaN        Taiwan*  2021-05-24 04:20:53  23.7
10   NaN    NaN            NaN        Taiwan*  2021-05-25 04:21:08  23.7
11   NaN    NaN            NaN        Taiwan*  2021-05-26 04:20:35  23.7
12   NaN    NaN            NaN        Taiwan*  2021-05-27 04:20:59  23.7
13   NaN    NaN            NaN        Taiwan*  2021-05-28 04:20:36  23.7
14   NaN    NaN            NaN        Taiwan*  2021-05-29 04:20:41  23.7
15   NaN    NaN            NaN        Taiwan*  2021-05-30 04:20:55  23.7
16   NaN    NaN            NaN        Taiwan*  2021-05-31 03:08:59  23.7
17   NaN    NaN            NaN        Taiwan*  2021-06-01 04:23:09  23.7

    Long_  Confirmed  Deaths  Recovered  Active Combined_Key  Incident_Rate  \
0   121.0       1290      12     1107.0   171.0      Taiwan*       5.416350
1   121.0       1475      12     1116.0   347.0      Taiwan*       6.193114
2   121.0       1682      12     1116.0   554.0      Taiwan*       7.062249
3   121.0       2017      12     1123.0   882.0      Taiwan*       8.468821
4   121.0       2260      14     1127.0  1119.0      Taiwan*       9.489110
5   121.0       2533      14     1133.0  1386.0      Taiwan*      10.635361
6   121.0       2825      15     1133.0  1677.0      Taiwan*      11.861388
7   121.0       3139      15     1133.0  1991.0      Taiwan*      13.179786
8   121.0       3862      17     1133.0  2712.0      Taiwan*      16.215462
9   121.0       4322      23     1133.0  3166.0      Taiwan*      18.146873
10  121.0       4917      29     1133.0  3755.0      Taiwan*      20.645113
11  121.0       5456      35     1133.0  4288.0      Taiwan*      22.908223
12  121.0       6091      46     1133.0  4912.0      Taiwan*      25.574411
13  121.0       6761      59     1133.0  5569.0      Taiwan*      28.387555
14  121.0       7315      78     1133.0  6104.0      Taiwan*      30.713646
15  121.0       7806      99     1133.0  6574.0      Taiwan*      32.775218
16  121.0       8160     109     1133.0  6918.0      Taiwan*      34.261566
17  121.0       8511     124     1133.0  7254.0      Taiwan*      35.735317

    Case_Fatality_Ratio
0              0.930233
1              0.813559
2              0.713436
3              0.594943
4              0.619469
5              0.552704
6              0.530973
7              0.477859
8              0.440186
9              0.532161
10             0.589791
11             0.641496
12             0.755213
13             0.872652
14             1.066302
15             1.268255
16             1.335784
17             1.456938

In [19]:
for i in range(1,10):
    url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-0"+str(i)+"-2021.csv"
    df2 = pd.read_csv(url)
    df2 = df2[df2['Country_Region']=='Taiwan*']
    df = pd.concat([df, df2], ignore_index=True)
print(df)

    FIPS Admin2 Province_State Country_Region          Last_Update   Lat  \
0    NaN    NaN            NaN        Taiwan*  2021-05-15 04:20:58  23.7
1    NaN    NaN            NaN        Taiwan*  2021-05-16 04:20:49  23.7
2    NaN    NaN            NaN        Taiwan*  2021-05-17 04:20:34  23.7
3    NaN    NaN            NaN        Taiwan*  2021-05-18 04:20:33  23.7
4    NaN    NaN            NaN        Taiwan*  2021-05-19 04:20:42  23.7
5    NaN    NaN            NaN        Taiwan*  2021-05-20 04:21:05  23.7
6    NaN    NaN            NaN        Taiwan*  2021-05-21 04:20:43  23.7
7    NaN    NaN            NaN        Taiwan*  2021-05-22 04:20:45  23.7
8    NaN    NaN            NaN        Taiwan*  2021-05-23 04:20:51  23.7
9    NaN    NaN            NaN        Taiwan*  2021-05-24 04:20:53  23.7
10   NaN    NaN            NaN        Taiwan*  2021-05-25 04:21:08  23.7
11   NaN    NaN            NaN        Taiwan*  2021-05-26 04:20:35  23.7
12   NaN    NaN            NaN        Taiwan*  2021-05-27 04:20:59  23.7
13   NaN    NaN            NaN        Taiwan*  2021-05-28 04:20:36  23.7
14   NaN    NaN            NaN        Taiwan*  2021-05-29 04:20:41  23.7
15   NaN    NaN            NaN        Taiwan*  2021-05-30 04:20:55  23.7
16   NaN    NaN            NaN        Taiwan*  2021-05-31 03:08:59  23.7
17   NaN    NaN            NaN        Taiwan*  2021-06-01 04:23:09  23.7
18   NaN    NaN            NaN        Taiwan*  2021-06-02 04:24:34  23.7
19   NaN    NaN            NaN        Taiwan*  2021-06-03 04:23:32  23.7
20   NaN    NaN            NaN        Taiwan*  2021-06-04 04:23:37  23.7
21   NaN    NaN            NaN        Taiwan*  2021-06-05 04:23:03  23.7
22   NaN    NaN            NaN        Taiwan*  2021-06-06 04:24:03  23.7
23   NaN    NaN            NaN        Taiwan*  2021-06-07 04:22:51  23.7
24   NaN    NaN            NaN        Taiwan*  2021-06-08 04:22:35  23.7
25   NaN    NaN            NaN        Taiwan*  2021-06-09 04:23:31  23.7
26   NaN    NaN            NaN        Taiwan*  2021-06-10 04:23:17  23.7

    Long_  Confirmed  Deaths  Recovered   Active Combined_Key  Incident_Rate  \
0   121.0       1290      12     1107.0    171.0      Taiwan*       5.416350
1   121.0       1475      12     1116.0    347.0      Taiwan*       6.193114
2   121.0       1682      12     1116.0    554.0      Taiwan*       7.062249
3   121.0       2017      12     1123.0    882.0      Taiwan*       8.468821
4   121.0       2260      14     1127.0   1119.0      Taiwan*       9.489110
5   121.0       2533      14     1133.0   1386.0      Taiwan*      10.635361
6   121.0       2825      15     1133.0   1677.0      Taiwan*      11.861388
7   121.0       3139      15     1133.0   1991.0      Taiwan*      13.179786
8   121.0       3862      17     1133.0   2712.0      Taiwan*      16.215462
9   121.0       4322      23     1133.0   3166.0      Taiwan*      18.146873
10  121.0       4917      29     1133.0   3755.0      Taiwan*      20.645113
11  121.0       5456      35     1133.0   4288.0      Taiwan*      22.908223
12  121.0       6091      46     1133.0   4912.0      Taiwan*      25.574411
13  121.0       6761      59     1133.0   5569.0      Taiwan*      28.387555
14  121.0       7315      78     1133.0   6104.0      Taiwan*      30.713646
15  121.0       7806      99     1133.0   6574.0      Taiwan*      32.775218
16  121.0       8160     109     1133.0   6918.0      Taiwan*      34.261566
17  121.0       8511     124     1133.0   7254.0      Taiwan*      35.735317
18  121.0       8842     137     1133.0   7572.0      Taiwan*      37.125094
19  121.0       9389     149     1133.0   8107.0      Taiwan*      39.421794
20  121.0       9974     166     1133.0   8675.0      Taiwan*      41.878046
21  121.0      10446     187     1133.0   9126.0      Taiwan*      43.859842
22  121.0      10956     224     1133.0   9599.0      Taiwan*      46.001190
23  121.0      11298     260     1133.0   9905.0      Taiwan*      47.437153
24  121.0      11491     286     1133.0  10072.0      Taiwan*      48.247506
25  121.0      11694     308     1133.0  10253.0      Taiwan*      49.099847
26  121.0      11968     333     1133.0  10502.0      Taiwan*      50.250296

    Case_Fatality_Ratio
0              0.930233
1              0.813559
2              0.713436
3              0.594943
4              0.619469
5              0.552704
6              0.530973
7              0.477859
8              0.440186
9              0.532161
10             0.589791
11             0.641496
12             0.755213
13             0.872652
14             1.066302
15             1.268255
16             1.335784
17             1.456938
18             1.549423
19             1.586963
20             1.664327
21             1.790159
22             2.044542
23             2.301292
24             2.488904
25             2.633829
26             2.782420

In [20]:
for i in range(10,12):
    url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-"+str(i)+"-2021.csv"
    df2 = pd.read_csv(url)
    df2 = df2[df2['Country_Region']=='Taiwan*']
    df = pd.concat([df, df2], ignore_index=True)
print(df.head())

   FIPS Admin2 Province_State Country_Region          Last_Update   Lat  \
0   NaN    NaN            NaN        Taiwan*  2021-05-15 04:20:58  23.7
1   NaN    NaN            NaN        Taiwan*  2021-05-16 04:20:49  23.7
2   NaN    NaN            NaN        Taiwan*  2021-05-17 04:20:34  23.7
3   NaN    NaN            NaN        Taiwan*  2021-05-18 04:20:33  23.7
4   NaN    NaN            NaN        Taiwan*  2021-05-19 04:20:42  23.7

   Long_  Confirmed  Deaths  Recovered  Active Combined_Key  Incident_Rate  \
0  121.0       1290      12     1107.0   171.0      Taiwan*       5.416350
1  121.0       1475      12     1116.0   347.0      Taiwan*       6.193114
2  121.0       1682      12     1116.0   554.0      Taiwan*       7.062249
3  121.0       2017      12     1123.0   882.0      Taiwan*       8.468821
4  121.0       2260      14     1127.0  1119.0      Taiwan*       9.489110

   Case_Fatality_Ratio
0             0.930233
1             0.813559
2             0.713436
3             0.594943
4             0.619469

In [79]:
df = pd.read_csv('DATASHEETS_COVD19_6/COVID19_6.csv', encoding="utf_8_sig")
print(df.head())

   Unnamed: 0  Unnamed: 0.1  FIPS  Admin2  Province_State Country_Region  \
0           0           0.0   NaN     NaN             NaN        Taiwan*
1           1           1.0   NaN     NaN             NaN        Taiwan*
2           2           2.0   NaN     NaN             NaN        Taiwan*
3           3           3.0   NaN     NaN             NaN        Taiwan*
4           4           4.0   NaN     NaN             NaN        Taiwan*

           Last_Update   Lat  Long_  Confirmed  ...  Recovered  Active  \
0  2021-05-15 04:20:58  23.7  121.0       1290  ...     1107.0   171.0
1  2021-05-16 04:20:49  23.7  121.0       1475  ...     1116.0   347.0
2  2021-05-17 04:20:34  23.7  121.0       1682  ...     1116.0   554.0
3  2021-05-18 04:20:33  23.7  121.0       2017  ...     1123.0   882.0
4  2021-05-19 04:20:42  23.7  121.0       2260  ...     1127.0  1119.0

   Combined_Key Incident_Rate  Case_Fatality_Ratio  Confirmed_shift  \
0       Taiwan*      5.416350             0.930233              NaN
1       Taiwan*      6.193114             0.813559           1290.0
2       Taiwan*      7.062249             0.713436           1475.0
3       Taiwan*      8.468821             0.594943           1682.0
4       Taiwan*      9.489110             0.619469           2017.0

   Newly Confirmed  Deaths_Shift  Newly Deaths           All_Update
0              NaN           NaN           NaN  2021-06-13 14-05-48
1            185.0          12.0           0.0  2021-06-13 14-05-48
2            207.0          12.0           0.0  2021-06-13 14-05-48
3            335.0          12.0           0.0  2021-06-13 14-05-48
4            243.0          12.0           2.0  2021-06-13 14-05-48

[5 rows x 21 columns]

In [82]:
import time
from datetime import timedelta, datetime
yesterday = datetime.today() + timedelta(-1)
timestr_yesterday = yesterday.strftime("%m-%d-%Y")
url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/"+timestr_yesterday+".csv"
print(url)
# df2 = pd.read_csv(url)
# df2 = df2[df2['Country_Region']=='Taiwan*']
# df2['Confirmed_shift'] = 0
# df2['Newly Confirmed'] = 0
# #資料全部更新時間
# time_update = time.strftime("%Y-%m-%d %H-%M-%S") 
# df2['All_Update'] = time_update
# df = pd.concat([df, df2], ignore_index=True)
# print(df)

https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2021.csv

In [70]:
df['Confirmed_shift'] = df["Confirmed"].shift(1)
df['Newly Confirmed'] = df['Confirmed'] - df['Confirmed_shift']

df['Deaths_Shift'] = df["Deaths"].shift(1)
df['Newly Deaths'] = df['Deaths'] - df['Deaths_Shift']

df.tail()

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Confirmed_shift,Newly Confirmed,Deaths_Shift,Newly Deaths,All_Update
25,25.0,NaN,NaN,NaN,Taiwan*,2021-06-09 04:23:31,23.7,121.0,11694,308,1133.0,10253.0,Taiwan*,49.099847,2.633829,11491.0,203.0,286.0,22.0,2021-06-13 14-05-48
26,26.0,NaN,NaN,NaN,Taiwan*,2021-06-10 04:23:17,23.7,121.0,11968,333,1133.0,10502.0,Taiwan*,50.250296,2.782420,11694.0,274.0,308.0,25.0,2021-06-13 14-05-48
27,27.0,NaN,NaN,NaN,Taiwan*,2021-06-11 04:23:20,23.7,121.0,12222,361,1133.0,10728.0,Taiwan*,51.316771,2.953690,11968.0,254.0,333.0,28.0,2021-06-13 14-05-48
28,28.0,NaN,NaN,NaN,Taiwan*,2021-06-12 04:22:22,23.7,121.0,12500,385,1133.0,10982.0,Taiwan*,52.484016,3.080000,12222.0,278.0,361.0,24.0,2021-06-13 14-05-48
29,NaN,NaN,NaN,NaN,Taiwan*,2021-06-13 04:22:44,23.7,121.0,12746,411,1133.0,11202.0,Taiwan*,53.516901,3.224541,12500.0,246.0,385.0,26.0,2021-06-13 14-47-27

In [57]:
# df = pd.read_csv('DATASHEETS_COVD19_6/COVID19_6.csv', encoding="utf_8_sig")
# df

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Confirmed_shift,Newly Confirmed,Deaths_Shift,Newly Deaths
0,0,NaN,NaN,NaN,Taiwan*,2021-05-15 04:20:58,23.7,121.0,1290,12,1107.0,171.0,Taiwan*,5.416350,0.930233,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,Taiwan*,2021-05-16 04:20:49,23.7,121.0,1475,12,1116.0,347.0,Taiwan*,6.193114,0.813559,1290.0,185.0,12.0,0.0
2,2,NaN,NaN,NaN,Taiwan*,2021-05-17 04:20:34,23.7,121.0,1682,12,1116.0,554.0,Taiwan*,7.062249,0.713436,1475.0,207.0,12.0,0.0
3,3,NaN,NaN,NaN,Taiwan*,2021-05-18 04:20:33,23.7,121.0,2017,12,1123.0,882.0,Taiwan*,8.468821,0.594943,1682.0,335.0,12.0,0.0
4,4,NaN,NaN,NaN,Taiwan*,2021-05-19 04:20:42,23.7,121.0,2260,14,1127.0,1119.0,Taiwan*,9.489110,0.619469,2017.0,243.0,12.0,2.0
5,5,NaN,NaN,NaN,Taiwan*,2021-05-20 04:21:05,23.7,121.0,2533,14,1133.0,1386.0,Taiwan*,10.635361,0.552704,2260.0,273.0,14.0,0.0
6,6,NaN,NaN,NaN,Taiwan*,2021-05-21 04:20:43,23.7,121.0,2825,15,1133.0,1677.0,Taiwan*,11.861388,0.530973,2533.0,292.0,14.0,1.0
7,7,NaN,NaN,NaN,Taiwan*,2021-05-22 04:20:45,23.7,121.0,3139,15,1133.0,1991.0,Taiwan*,13.179786,0.477859,2825.0,314.0,15.0,0.0
8,8,NaN,NaN,NaN,Taiwan*,2021-05-23 04:20:51,23.7,121.0,3862,17,1133.0,2712.0,Taiwan*,16.215462,0.440186,3139.0,723.0,15.0,2.0
9,9,NaN,NaN,NaN,Taiwan*,2021-05-24 04:20:53,23.7,121.0,4322,23,1133.0,3166.0,Taiwan*,18.146873,0.532161,3862.0,460.0,17.0,6.0
10,10,NaN,NaN,NaN,Taiwan*,2021-05-25 04:21:08,23.7,121.0,4917,29,1133.0,3755.0,Taiwan*,20.645113,0.589791,4322.0,595.0,23.0,6.0
11,11,NaN,NaN,NaN,Taiwan*,2021-05-26 04:20:35,23.7,121.0,5456,35,1133.0,4288.0,Taiwan*,22.908223,0.641496,4917.0,539.0,29.0,6.0
12,12,NaN,NaN,NaN,Taiwan*,2021-05-27 04:20:59,23.7,121.0,6091,46,1133.0,4912.0,Taiwan*,25.574411,0.755213,5456.0,635.0,35.0,11.0
13,13,NaN,NaN,NaN,Taiwan*,2021-05-28 04:20:36,23.7,121.0,6761,59,1133.0,5569.0,Taiwan*,28.387555,0.872652,6091.0,670.0,46.0,13.0
14,14,NaN,NaN,NaN,Taiwan*,2021-05-29 04:20:41,23.7,121.0,7315,78,1133.0,6104.0,Taiwan*,30.713646,1.066302,6761.0,554.0,59.0,19.0
15,15,NaN,NaN,NaN,Taiwan*,2021-05-30 04:20:55,23.7,121.0,7806,99,1133.0,6574.0,Taiwan*,32.775218,1.268255,7315.0,491.0,78.0,21.0
16,16,NaN,NaN,NaN,Taiwan*,2021-05-31 03:08:59,23.7,121.0,8160,109,1133.0,6918.0,Taiwan*,34.261566,1.335784,7806.0,354.0,99.0,10.0
17,17,NaN,NaN,NaN,Taiwan*,2021-06-01 04:23:09,23.7,121.0,8511,124,1133.0,7254.0,Taiwan*,35.735317,1.456938,8160.0,351.0,109.0,15.0
18,18,NaN,NaN,NaN,Taiwan*,2021-06-02 04:24:34,23.7,121.0,8842,137,1133.0,7572.0,Taiwan*,37.125094,1.549423,8511.0,331.0,124.0,13.0
19,19,NaN,NaN,NaN,Taiwan*,2021-06-03 04:23:32,23.7,121.0,9389,149,1133.0,8107.0,Taiwan*,39.421794,1.586963,8842.0,547.0,137.0,12.0
20,20,NaN,NaN,NaN,Taiwan*,2021-06-04 04:23:37,23.7,121.0,9974,166,1133.0,8675.0,Taiwan*,41.878046,1.664327,9389.0,585.0,149.0,17.0
21,21,NaN,NaN,NaN,Taiwan*,2021-06-05 04:23:03,23.7,121.0,10446,187,1133.0,9126.0,Taiwan*,43.859842,1.790159,9974.0,472.0,166.0,21.0
22,22,NaN,NaN,NaN,Taiwan*,2021-06-06 04:24:03,23.7,121.0,10956,224,1133.0,9599.0,Taiwan*,46.001190,2.044542,10446.0,510.0,187.0,37.0
23,23,NaN,NaN,NaN,Taiwan*,2021-06-07 04:22:51,23.7,121.0,11298,260,1133.0,9905.0,Taiwan*,47.437153,2.301292,10956.0,342.0,224.0,36.0
24,24,NaN,NaN,NaN,Taiwan*,2021-06-08 04:22:35,23.7,121.0,11491,286,1133.0,10072.0,Taiwan*,48.247506,2.488904,11298.0,193.0,260.0,26.0
25,25,NaN,NaN,NaN,Taiwan*,2021-06-09 04:23:31,23.7,121.0,11694,308,1133.0,10253.0,Taiwan*,49.099847,2.633829,11491.0,203.0,286.0,22.0
26,26,NaN,NaN,NaN,Taiwan*,2021-06-10 04:23:17,23.7,121.0,11968,333,1133.0,10502.0,Taiwan*,50.250296,2.782420,11694.0,274.0,308.0,25.0
27,27,NaN,NaN,NaN,Taiwan*,2021-06-11 04:23:20,23.7,121.0,12222,361,1133.0,10728.0,Taiwan*,51.316771,2.953690,11968.0,254.0,333.0,28.0
28,28,NaN,NaN,NaN,Taiwan*,2021-06-12 04:22:22,23.7,121.0,12500,385,1133.0,10982.0,Taiwan*,52.484016,3.080000,12222.0,278.0,361.0,24.0

In [58]:
# #資料全部更新時間
# import time
# time_update = time.strftime("%Y-%m-%d %H-%M-%S") 
# time_update
# df['All_Update'] = time_update
# df.tail()

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio,Confirmed_shift,Newly Confirmed,Deaths_Shift,Newly Deaths,All_Update
0,0,NaN,NaN,NaN,Taiwan*,2021-05-15 04:20:58,23.7,121.0,1290,12,1107.0,171.0,Taiwan*,5.416350,0.930233,NaN,NaN,NaN,NaN,2021-06-13 14-05-48
1,1,NaN,NaN,NaN,Taiwan*,2021-05-16 04:20:49,23.7,121.0,1475,12,1116.0,347.0,Taiwan*,6.193114,0.813559,1290.0,185.0,12.0,0.0,2021-06-13 14-05-48
2,2,NaN,NaN,NaN,Taiwan*,2021-05-17 04:20:34,23.7,121.0,1682,12,1116.0,554.0,Taiwan*,7.062249,0.713436,1475.0,207.0,12.0,0.0,2021-06-13 14-05-48
3,3,NaN,NaN,NaN,Taiwan*,2021-05-18 04:20:33,23.7,121.0,2017,12,1123.0,882.0,Taiwan*,8.468821,0.594943,1682.0,335.0,12.0,0.0,2021-06-13 14-05-48
4,4,NaN,NaN,NaN,Taiwan*,2021-05-19 04:20:42,23.7,121.0,2260,14,1127.0,1119.0,Taiwan*,9.489110,0.619469,2017.0,243.0,12.0,2.0,2021-06-13 14-05-48

In [ ]:
#儲存資料
import time
timestr = time.strftime("%Y%m%d")
df.to_csv('DATASHEETS_COVD19_6/COVID19_6_'+timestr+'.csv', encoding="utf_8_sig")

In [72]:
# google sheets authentication
Json = './covid19.json'
Url = ['https://spreadsheets.google.com/feeds']

In [73]:
# 連線到資料表
Connect = SAC.from_json_keyfile_name(Json, Url)
GoogleSheets = gspread.authorize(Connect)

In [74]:
# 開啟資料表及工作表
Sheet = GoogleSheets.open_by_key('1Tw0_YTw9rq4WKzO1uD8mrGIGdLQAdSekmkpiWDft4TE')
# Sheets = Sheet.sheet1

In [75]:
# 查看此 GoogleSheet 內 Sheet 清單
wks_list = Sheet.worksheets()
print(wks_list)

[<Worksheet '工作表1' id:0>]

In [76]:
#選取by名稱
worksheet = Sheet.sheet1

In [77]:
#寫入資料
set_with_dataframe(worksheet, df)
print("寫入成功")

寫入成功